"use client"
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Activity, ShieldAlert, HeartPulse } from 'lucide-react'

export default function CitizenPortal() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl space-y-8">
        <header className="text-center mb-12">
          <h1 className="text-4xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 to-cyan-500">
            UrbanSense Citizen Portal
          </h1>
          <p className="text-slate-400 mt-2">Real-time localized air quality & health advisories.</p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <Card className="bg-slate-900 border-slate-800">
            <CardHeader>
              <CardTitle className="text-emerald-400 flex items-center gap-2">
                <Activity size={24} /> Current Local AQI
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-6xl font-bold text-slate-100 text-center py-8">
                85
                <div className="text-lg text-emerald-500 mt-2 font-normal">Moderate</div>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-slate-900 border-slate-800">
            <CardHeader>
              <CardTitle className="text-cyan-400 flex items-center gap-2">
                <HeartPulse size={24} /> AI Health Advisory
              </CardTitle>
            </CardHeader>
            <CardContent className="h-full">
              <div className="bg-slate-950 p-6 rounded-lg border border-slate-800 text-slate-300 text-lg leading-relaxed h-[180px] flex items-center">
                &quot;Air quality is acceptable for most individuals. However, unusually sensitive people should consider limiting prolonged outdoor exertion.&quot;
                <br /><br />
                <span className="text-sm text-slate-500 italic">- Generated by UrbanSense Health Agent</span>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
